### ISSUE TITLE
idiomatic.js

### ISSUE THREAD

**Issue by mpiccolino** [sencha/code-guidelines#4]
Perhaps worth mentioning [idiomatic.js](https://github.com/rwaldron/idiomatic.js/) in the resources as well?

**Comment by arthurakay** [comment]
I hadn't seen that before, and it certainly looks like a good resource.

The purpose of Sencha's repo (here) is that we wanted people to fork our guidelines and make them their own... so I'd encourage you to do just that and add the link :-)

We may update this repo over time, but for right now we wanted our list of resources to include content that *we* found particularly meaningful.

**Comment by mpiccolino** [comment]
ok, I see your point!
