### ISSUE TITLE
"japanese" Branch for Japanese translation.

### ISSUE THREAD

**Issue by shinobukawano** [sencha/code-guidelines#6]
I'd like to translate this excellent guideline to Japanese, our native language.

That's useful to add "japanese" branch so that we able to switch the language of this guideline. 
Japanese Sencha community and I will translate it and send a pull request to the branch.

Hope you considering about it. :) :santa:

**Comment by arthurakay** [comment]
Just go ahead and fork the repo, then issue a PR and someone can merge/add the branch. @dongryphon is likely to be that person :-)

**Comment by shinobukawano** [comment]
This issue was solved at #8 & #7.
